### ISSUE TITLE
Risk Lookup Table is wrong

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/domain-network#135]
The risk lookup table encoded in the `RiskLookupTable.csv` file does not match the number of levels actually used in the domain model. The lookup table used in the Java system-modeller code does.

This is less serious than it might be because the Java code has the lookup table encoded in its source code (it should be loading the lookup table from the domain model but it doesn't). However, the Python `risk-report` project does load such information from the domain model CSV files and failed as a result of the information being inconsistent with a system model being analysed.

**Comment by mike1813** [comment]
Reviewed the pull request, and actioned the merge into branch 6a. Left the branch open as there are several open development branches and we may want to merge this change into some of those before they get merged with 6a.
