### ISSUE TITLE
Replace "notebook" with "laptop"

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/domain-network#72]
According to my experience, and [Google search trends](https://trends.google.com/trends/explore?date=all&geo=GB&q=laptop,notebook&hl=en-GB), the word "laptop" is more common than "notebook". Some sources claim that laptops are larger than notebooks, but that seems to be the only distinction, and for our domain model, it is irrelevant.

I propose renaming laptop to be notebook.

![image](https://github.com/Spyderisk/domain-network/assets/4892991/61cf3df8-6f22-47c2-8a33-3bc13b121962)

**Comment by mike1813** [comment]
Should have refreshed the page. I missed this issue. See #74.

**Comment by mike1813** [comment]
Addressed in branch 73.

**Comment by mike1813** [comment]
Now merged into branch '6a'.
